config/routes.rb
Yesnooo::Application.routes.draw do
 
  match '/q/:page', :controller => 'qs', :action => 'index'
  match '/qr/', :controller => 'qs', :action => 'reload'
  match '/qs/:id/yes', :controller => 'qs', :action => 'yes'
  match '/qs/:id/no', :controller => 'qs', :action => 'no'
  match '/about', :controller => 'qs', :action => 'about'
  match '/u', :controller => 'qs', :action => 'user'

  resources :qs

  root :to => 'qs#index'

end

app/models/q.rb
class Q < ActiveRecord::Base
	validates :title, :presence => true
	has_attached_file :image_yes,
		:styles => 
		{
			:original => ["400x400#", :jpg]
		},
		:convert_options => {
			:original => "-quality 65 -strip -colorspace RGB"
		}

	has_attached_file :image_no,
		:styles => 
		{
			:original => ["400x400#", :jpg]
		},
		:convert_options => {
			:original => "-quality 65 -strip -colorspace RGB"
		}

	before_create :generate_unique_id

	def generate_unique_id
		self.unique_id = SecureRandom.urlsafe_base64(6, padding=false)
	end

	def to_param
		self.unique_id
	end

	attr_accessible :description, :title, :votes, :image_yes, :image_no, :unique_id, :votes_no, :votes_totes

	self.per_page = 10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/qs_controller.rb
require 'uri'

class QsController < ApplicationController
  # GET /qs
  # GET /qs.json

  def index

    @q_feature = Q.order('id DESC').all(:select => "*", :conditions => ["image_yes_file_name IS NOT NULL"]).shuffle.first

    if params[:pop]
      @qs = Q.paginate(:page => params[:page]).order('votes_totes DESC').all(:select => "*", :conditions => ["votes_totes > 25"])
    elsif params[:search]
      @qs = Q.paginate(:page => params[:page]).order('id DESC').where("upper(title) LIKE '%#{params[:search].upcase}%'")
    elsif params[:yes]
      @qs = Q.paginate(:page => params[:page]).order('id DESC').all(:select => "*", :conditions => ["votes > votes_no"])
    elsif params[:no]
      @qs = Q.paginate(:page => params[:page]).order('id DESC').all(:select => "*", :conditions => ["votes < votes_no"])
    else
      #limit = 10
      #@qs = Q.order('id DESC').limit(limit) -- for load more button
      @qs = Q.paginate(:page => params[:page]).order('id DESC').all
    end

    @q_next = Q.offset(rand(Q.count)).first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qs }
    end
  end

  def reload

    #@qs = Q.all.shuffle
    #limit = 10
    #@qs = Q.order('id DESC').offset(limit).all
    #respond_to do |format|
      #format.html # index.html.erb
      #format.json { render json: @qs }
    #end

  end

  def user

    @qs = Q.order('id DESC').all.shuffle

  end

  # GET /qs/1
  # GET /qs/1.json
  def show
    @q = Q.find_by_unique_id(params[:id])

    @q_next = Q.offset(rand(Q.count)).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @q }
    end
  end

  def yes

    @q = Q.find_by_unique_id(params[:id])

  end

  def no

    @q = Q.find_by_unique_id(params[:id])

  end

  # GET /qs/new
  # GET /qs/new.json
  def new
    @q = Q.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @q }
    end
  end

  # GET /qs/1/edit
  def edit
    @q = Q.find_by_unique_id(params[:id])
  end

  # POST /qs
  # POST /qs.json
  def create
    @q = Q.new(params[:q])

    respond_to do |format|
      if @q.save
        format.html { redirect_to @q, notice: 'Q was successfully created.' }
        format.json { render json: @q, status: :created, location: @q }
      else
        format.html { render action: "new" }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qs/1
  # PUT /qs/1.json
  def update
    @q = Q.find_by_unique_id(params[:id])

    respond_to do |format|
      if @q.update_attributes(params[:q])
        format.html { redirect_to @q, notice: 'Q was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @q.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qs/1
  # DELETE /qs/1.json
  def destroy
    @q = Q.find_by_unique_id(params[:id])
    @q.destroy

    respond_to do |format|
      format.html { redirect_to qs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def mobile_agent?
	  request.env["HTTP_USER_AGENT"] && request.env["HTTP_USER_AGENT"][/(iPhone|iPad|iPod|BlackBerry|Android)/]
	end
end

app/helpers/qs_helper.rb
module QsHelper
end

app/views/qs/_form.html.erb
<%= form_for(@q) do |f| %>
  <% if @q.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@q.errors.count, "error") %> prohibited this q from being saved:</h2>

      <ul>
      <% @q.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Your question:' %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, 'Add a little description for some context?' %>
    <%= f.text_area :description, :rows => 0, :cols => 0 %>
  </div>
  <div class="field">
    <%= f.label :image_yes, 'Add an image for Yes?' %>
    <%= f.file_field :image_yes, :accept => 'image/*' %>
  </div>
  <div class="field">
    <%= f.label :image_no, 'Add an image for No?' %>
    <%= f.file_field :image_no, :accept => 'image/*' %>
  </div>
  <!--<div class="field">
    <%#= f.label :votes %><br />
    <%#= f.number_field :votes %>
  </div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qs/about.html.erb
<p><span>yesno</span> is a simple app that allows users (without registering/logging in) to vote on yes or no questions. They can also create their own and share them socaily or with friends.</p>
<div class="beta">
	<p>This is still in uber-beta, and is mostly a side-project; so if anything wonks out, that&rsquo;s why. I&rsquo;ll do my best to fix it of course, but have a wee bit o&rsquo; patience please <span>☺</span></p>
	<h3>Known issues</h3>
	<p>I&rsquo;ve seen a few oddities with cookie for editing a question.</p>
</div
<hr />
<h2>To get started, follow these simple steps:</h2>
<ol>
	<li>from anywhere on the site, click <span>yes</span> in the logo to show only questions with a majority of <span>yes</span> answers <em>(give it a go now, we&rsquo;ll wait)</em></li>
	<li>conversly, clicking <span>no</span> will do the same for questions with a majority of <span>no</span> answers</li>
	<li>then, when you&rsquo;ve found a question that strikes your fancy, click the title</li>
	<li>from the question detail page, simply click or tap <span>yes</span> or <span>no</span> to vote</li>
	<li>then, you&rsquo;ll see the results so far</li>
	<li>now, feel free to share this on Twitter or Facebook, or <span>yesno</span> give you two URLs (click <span class="icon-share-alt"></span> to view these as well as sharing links) you can share that users can auto-vote <span>yes</span> or <span>no</span> with by simply visiting that URL</li>
	<li>and voila, that&rsquo;s it</li>
</ol>
<hr />
<h2>Easy as pie, no?</h2>
<p>You can then <span class="icon-repeat"></span> to get a new question, or you can <span class="icon-search"></span> for another question as well. Also, clicking the <span class="icon-star"></span> will filter the questions by only those with more than 25 total votes.</p>
<hr />
<h2>Or you can create your own question:</h2>
<ol>
	<li>click the <span class="icon-plus"></span> to get started</li>
	<li>add in a title <span>(required)</span>, a description (optional), and 2 images if you feel it will help the user decide</li>
	<li>lastly, hit publish and off you go</li>
</ol>
<hr />
<h2>Cookies, hmmmm?</h2>
<p>Yep, you got it. This site extensively uses cookies to track your responses and actions. I don&rsquo;t do <span>ANYTHING</span> with them of course, and I won&rsquo;t ever sell the data or anyting like that. So yes, you could delete the cookie and game the system, but what would be the fun in that?</p>
<p>Another reason for using cookies is so that you don&rsquo;t need to create another user account that you&rsquo;ll [probably] struggle to remember the password to, and it just makes the site easier to use and enjoy.</p>
<hr />
<h2>Want to add a question?</h2>
<div class="center">
  <%= link_to(new_q_path) do %>
  <span class="btn"><span class="icon-plus"></span> Let&rsquo;s do it!</span>
  <% end %>
</div>
<hr />
<h2>Questions or bugs?</h2>
<p><a href="https://github.com/jefffis/yesno" class="b">Check the project on Github</a>, or <a href="mailto:whatis@yesorno.es" class="b">send me an email</a>. Otherwise, enjoy!</p>
<hr />
<h2>Sign up for updates?</h2>
<p>I&rsquo;ll push out updates periodically (via Mailchimp, I &lt;3 them), so drop your name here if you&rsquo;re interested in that sort of thing; if not, ignore this part.</p>
<form action="http://jefff.us6.list-manage.com/subscribe/post?u=abd01cbfa99953914467e6b5f&amp;id=11edb1ae39" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate target="_blank">
	<fieldset>
		<label for="email">
			<input type="email" id="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your email" required>
		</label>
	</fieldset>
	<fieldset>
		<input type="submit" value="Join that hotness" />
	</fieldset>
</form>
<hr />
<%= link_to ('<span class="icon-home"></span> <em>home</em>').html_safe, '/', :class => 'popular' %>
<p>And yes, I was <span>inspired by the Polar &amp; Seesaw apps</span>; but I wanted something simpler and more focussed. Also, a hat-tip to <a href="https://twitter.com/DUQE" target="_blank" class="b">Duqe</a> for the voting via URLs concept.</p>
<hr />
<p>Lovingly made by <a class="inline b" href="http://jefff.co/" target="_blank">jefff</a></p>

app/views/qs/edit.html.erb
<% if cookies[@q.unique_id+'-author'] == 'yes' %>
<h1 class="none">Edit <span><%= @q.title %></span></h1>
<%= render 'form' %>
<div class="center del">
	<%= link_to 'Delete this question?'.html_safe, @q, method: :delete, data: { confirm: 'Are you sure? All data will be gone for good.' } %>
</div>
<div class="center">
	<%= link_to(@q) do %>
	<span class="icon-arrow-left"></span>
	<% end %>
	<%= link_to('/') do %>
	<span class="icon-home"></span>
	<% end %>
</div>
<% else %>
<div class="not-valid">
	<h1>Hmmm, looks like you didn&rsquo;t create this post.</h1>
	<p>That means, you shouldn&rsquo;t be editing it either ☹.</p>
	<div class="center btm">
		<%= link_to(new_q_path) do %>
		<span class="btn"><span class="icon-plus"></span> Add</span>
		<% end %>
		<%= link_to('/') do %>
		<span class="btn"><span class="icon-home"></span></span>
		<% end %>
	</div>
</div>
<% end %>

app/views/qs/index.html.erb
<%
vote_yes = params[:yes]
vote_no = params[:no]
pop = params[:pop]
srch = params[:search]
url = request.fullpath.split('?')
%>
<%#= url[0] %>
<% if @qs.length > 0 && !vote_yes && !vote_no && !pop && !srch %>
<% if  url[0] == '/' || url[0] == '/q/1' %>
<%
#featured
if @q_feature %>
<div id="load" class="load">
<div class="featured" id="featured" style="background-image: url(<%= @q_feature.image_yes.url(:original) %>); background-size: cover;">
    <!--<span class="icon-beaker rld" id="rld"></span>-->
    <%= link_to('/qs/'+@q_feature.unique_id) do %>
      <h1><%= @q_feature.title %></h1>
    <% end %>
</div>
</div>
<% end %>
<% end %>
<% end %>
<% if @qs.length > 0 %>
<ul class="listings" id="listings">
<%
# all qs
@qs.each do |q| %>
<%
yes_v = q.votes
no_v = q.votes_no
%>
  <li<% if url[0] == '/' && @q_feature.unique_id == q.unique_id %> class="hide"<% end %>>
    <%= link_to(q) do %>
    <h1<% if vote_no || !vote_no && no_v > yes_v %> class="no"<% end %>><%= q.title %></h1>
    <% if q.votes > 0 || q.votes_no > 0 %><small>
      <% if q.votes > 0 %><em><span class="icon-thumbs-up"></span> <%= q.votes %> votes</em><% end %>
      <% if q.votes_no > 0 %><em><span class="icon-thumbs-down"></span> <%= q.votes_no %> votes</em><% end %>
    </small><% end %>
    <% end %>
  </li>
<% end %>
</ul>
<%# if @qs.length > 10 && !vote_yes && !vote_no && !pop && !srch %>
<!--<div class="center"><span class="ldmr" id="ldmr">Load More <span class="icon-repeat"></span></span></div>-->
<%# end %>
<% else %>
<h1 class="none">Shucks, ain&rsquo;t no posts that meet that criteria.</h1>
<% end %>
<%= will_paginate @qs %>
<div class="center btm">
  <!--<%# if @qs.length > 0 && !vote_yes && !vote_no && !pop && !srch %>
  <%# if @q_next %>
  <%#= link_to('/qs/'+@q_next.unique_id) do %>
  <span class="btn<%# if vote_no %> rev<%# end %>"><span class="icon-repeat"></span> Randomize</span>
  <%# end %>
  <%# end %>
  <%# end %>-->
  <%= link_to(new_q_path) do %>
  <span class="btn<% if vote_no %> rev<% end %>"><span class="icon-plus"></span> Add?</span>
  <% end %>
</div>

app/views/qs/new.html.erb
<!--<h1>New q</h1>-->
<%= render 'form' %>
<div class="center">
<a onclick="goBack()">
	<span class="icon-arrow-left"></span>
</a>
<script>
	function goBack(){
		window.history.back();
	}
</script>
</div>

app/views/qs/no.html.erb
<div class="hide">
<%= form_for(@q) do |q| %>
	<%= q.hidden_field :votes %>
	<%= q.hidden_field :votes_no %>
	<%= q.hidden_field :votes_totes %>
<% end %>
</div>

app/views/qs/reload.html.erb
[<%
i=0
@qs.each_with_index do |q,i| %>
	{
		"title": <%= raw(q.title.to_json) %>,
		"link": <%= raw(q.unique_id.to_json) %>
	}<% if i == @qs.length - 1 %><% else %>,<% end %>
<%
i+=1
end %>]

app/views/qs/user.html.erb
<% usr = cookies[:usr] %>
<% if usr %>
<h2 class="usr">Questions you asked:</h2>
<ul class="listings">
<% @qs.each do |q| %>
	<% if cookies[q.unique_id+'-author'] %>
	<li>
		<%= link_to(q) do %>
			<h1><%= q.title %></h1>
		<% end %>
	</li>
	<% end %>
<% end %>
</ul>
<%= link_to ('<span class="icon-home"></span> <em>home</em>').html_safe, '/', :class => 'popular hm' %>
<% end %>

app/views/qs/yes.html.erb
<div class="hide">
<%= form_for(@q) do |q| %>
	<%= q.hidden_field :votes %>
	<%= q.hidden_field :votes_no %>
	<%= q.hidden_field :votes_totes %>
<% end %>
</div>